# Generated by Django 3.0 on 2021-09-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210909_1335'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_Cart',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_IngredientRecipe',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_Cart'),
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_IngredientRecipe'),
        ),
    ]
