# Generated by Django 3.0 on 2021-09-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210909_1336'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_IngredientRecipe',
        ),
    ]
